-- No-op migration retained for history compatibility.
--
-- The current VitaVault baseline migration (0_init) already creates the device/mobile
-- sync schema that this migration originally introduced:
--   - ReadingSource
--   - DevicePlatform
--   - DeviceConnectionStatus
--   - SyncJobStatus
--   - DeviceReadingType
--   - DeviceConnection
--   - DeviceReading
--   - MobileSessionToken
--   - SyncJob
--   - VitalRecord.externalReadingId
--   - VitalRecord.readingSource
--
-- Keeping those CREATE TYPE / CREATE TABLE statements here makes Prisma shadow
-- database validation fail with errors such as:
--   ERROR: type "ReadingSource" already exists
--
-- This migration is intentionally left blank so the migration chain can validate
-- cleanly after the schema was consolidated into 0_init.
