import { AppShell } from "@/components/app-shell";
import { PageHeader } from "@/components/common";
import { saveHealthProfile } from "@/app/actions";
import { requireUser } from "@/lib/session";
import { db } from "@/lib/db";
import { Button, Card, CardContent, Input, Label, Select, Textarea } from "@/components/ui";

export default async function HealthProfilePage() {
  const user = await requireUser();
  const profile = await db.healthProfile.findUnique({ where: { userId: user.id } });
  return <AppShell><PageHeader title="Health Profile" description="Maintain your baseline information, emergency contact, allergies, and chronic conditions." /><Card><CardContent className="pt-6"><form action={saveHealthProfile} className="grid gap-5 md:grid-cols-2"><div className="space-y-2 md:col-span-2"><Label>Full name</Label><Input name="fullName" defaultValue={profile?.fullName ?? user.name ?? ""} required /></div><div className="space-y-2"><Label>Date of birth</Label><Input type="date" name="dateOfBirth" defaultValue={profile?.dateOfBirth ? new Date(profile.dateOfBirth).toISOString().slice(0,10) : ""} /></div><div className="space-y-2"><Label>Sex</Label><Select name="sex" defaultValue={profile?.sex ?? ""}><option value="">Select</option><option value="MALE">Male</option><option value="FEMALE">Female</option><option value="OTHER">Other</option><option value="PREFER_NOT_TO_SAY">Prefer not to say</option></Select></div><div className="space-y-2"><Label>Blood type</Label><Input name="bloodType" defaultValue={profile?.bloodType ?? ""} /></div><div className="space-y-2"><Label>Height (cm)</Label><Input type="number" step="0.1" name="heightCm" defaultValue={profile?.heightCm ?? ""} /></div><div className="space-y-2"><Label>Weight (kg)</Label><Input type="number" step="0.1" name="weightKg" defaultValue={profile?.weightKg ?? ""} /></div><div className="space-y-2"><Label>Emergency contact name</Label><Input name="emergencyContactName" defaultValue={profile?.emergencyContactName ?? ""} /></div><div className="space-y-2"><Label>Emergency contact phone</Label><Input name="emergencyContactPhone" defaultValue={profile?.emergencyContactPhone ?? ""} /></div><div className="space-y-2 md:col-span-2"><Label>Chronic conditions</Label><Textarea name="chronicConditions" defaultValue={profile?.chronicConditions ?? ""} /></div><div className="space-y-2 md:col-span-2"><Label>Allergies summary</Label><Textarea name="allergiesSummary" defaultValue={profile?.allergiesSummary ?? ""} /></div><div className="space-y-2 md:col-span-2"><Label>Notes</Label><Textarea name="notes" defaultValue={profile?.notes ?? ""} /></div><div className="md:col-span-2"><Button>Save profile</Button></div></form></CardContent></Card></AppShell>;
}
