-- Migration intentionally kept as a no-op.
--
-- The care-team and AI insight objects that this migration name refers to are
-- already included in the earlier baseline migration (`0_init`) in this branch.
-- Keeping the original SQL here caused Prisma shadow database validation to fail
-- because it attempted to recreate existing enums and tables such as:
-- - MedicationStatus
-- - AppointmentStatus
-- - LabFlag
-- - SymptomSeverity
-- - CareAccessRole
-- - CareAccessStatus
-- - User
-- - CareAccess
-- - CareInvite
-- - AccessAuditLog
-- - AiInsight
--
-- This no-op file preserves the migration folder name/order while preventing
-- duplicate CREATE TYPE / CREATE TABLE statements from breaking `prisma migrate dev`.
