import Link from "next/link";
import { Activity, AlertTriangle, ArrowRight, CheckCircle2, DatabaseZap, FileText, HeartPulse, ShieldCheck, Smartphone, Sparkles, Users } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { PageHeader, StatusPill } from "@/components/common";
import { Badge, Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui";
import { getDataQualityCenterData, type DataQualityItem, type DataQualitySection, type DataQualityTone } from "@/lib/data-quality";
import { requireUser } from "@/lib/session";

const categoryIcons = { profile: ShieldCheck, records: HeartPulse, safety: AlertTriangle, devices: Smartphone, reports: FileText, collaboration: Users };
function scoreTone(score: number): DataQualityTone { return score >= 85 ? "success" : score >= 70 ? "info" : score >= 45 ? "warning" : "danger"; }
function severityTone(severity: DataQualityItem["severity"]): DataQualityTone { return severity === "critical" ? "danger" : severity === "warning" ? "warning" : severity === "info" ? "info" : "success"; }
function ProgressBar({ value }: { value: number }) { return <div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div>; }
function QualityActionCard({ item }: { item: DataQualityItem }) { return <Link href={item.href} className="block rounded-2xl border border-border/60 bg-background/60 p-4 transition hover:-translate-y-0.5 hover:bg-muted/40 hover:shadow-sm"><div className="flex items-start justify-between gap-3"><div className="space-y-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{item.title}</p><StatusPill tone={severityTone(item.severity)}>{item.severity}</StatusPill></div><p className="text-sm leading-6 text-muted-foreground">{item.description}</p><p className="text-xs font-medium text-muted-foreground">Evidence: {item.evidence}</p></div><ArrowRight className="mt-1 h-4 w-4 shrink-0 text-muted-foreground" /></div><div className="mt-3 inline-flex items-center rounded-xl bg-primary/10 px-3 py-1 text-xs font-medium text-primary">{item.action}</div></Link>; }
function QualitySectionCard({ section }: { section: DataQualitySection }) { const Icon = categoryIcons[section.id]; return <Card className="h-full"><CardHeader><div className="flex items-start justify-between gap-4"><div className="flex items-start gap-3"><div className="rounded-2xl bg-primary/10 p-2 text-primary"><Icon className="h-5 w-5" /></div><div><CardTitle>{section.title}</CardTitle><CardDescription className="mt-1 leading-6">{section.description}</CardDescription></div></div><StatusPill tone={section.tone}>{section.score}%</StatusPill></div></CardHeader><CardContent className="space-y-4"><ProgressBar value={section.score} /><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{section.metrics.map((metric) => <div key={metric.label} className="rounded-2xl border border-border/60 bg-background/50 p-3"><div className="flex items-center justify-between gap-2"><p className="text-xs font-medium text-muted-foreground">{metric.label}</p><StatusPill tone={metric.tone}>{metric.value}</StatusPill></div><p className="mt-2 text-xs leading-5 text-muted-foreground">{metric.description}</p></div>)}</div>{section.items.length > 0 ? <div className="space-y-3">{section.items.map((item) => <QualityActionCard key={item.id} item={item} />)}</div> : <div className="rounded-2xl border border-emerald-200/70 bg-emerald-50/70 p-4 text-sm leading-6 text-emerald-800 dark:border-emerald-900/50 dark:bg-emerald-950/30 dark:text-emerald-200"><div className="flex items-start gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0" /><p>No major gaps detected in this section.</p></div></div>}</CardContent></Card>; }

export default async function DataQualityPage() {
  const user = await requireUser();
  const data = await getDataQualityCenterData(user.id);
  return <AppShell><div className="mx-auto max-w-7xl space-y-6 p-6"><PageHeader title="Data Quality Center" description="A reviewer-friendly health data cleanup workspace for profile gaps, stale records, safety issues, device sync health, export readiness, and care-team handoffs." action={<div className="flex flex-wrap gap-2"><Link href="/report-builder" className="inline-flex items-center justify-center gap-2 rounded-2xl border border-border/70 bg-background/70 px-4 py-2.5 text-sm font-medium transition hover:bg-muted/50"><FileText className="h-4 w-4" />Report Builder</Link><Link href="/device-connection" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-primary px-4 py-2.5 text-sm font-medium text-primary-foreground shadow-sm transition hover:opacity-95"><Smartphone className="h-4 w-4" />Device Integrations</Link></div>} />
  <Card className="overflow-hidden rounded-[34px] border-border/60 shadow-sm"><CardContent className="p-0"><div className="grid gap-0 xl:grid-cols-[1.15fr_0.85fr]"><div className="space-y-6 p-6 sm:p-8"><div className="flex flex-wrap items-center gap-3"><StatusPill tone={scoreTone(data.summary.score)}>{data.summary.readinessLabel}</StatusPill><StatusPill tone={data.summary.criticalItems > 0 ? "danger" : data.summary.warningItems > 0 ? "warning" : "success"}>{data.summary.criticalItems} critical / {data.summary.warningItems} warning</StatusPill></div><div><p className="text-sm font-semibold uppercase tracking-[0.24em] text-muted-foreground">Quality command center</p><h2 className="mt-3 max-w-3xl text-3xl font-semibold leading-tight tracking-tight sm:text-5xl">Make VitaVault data cleaner before reports, care-team sharing, and device-driven monitoring.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-muted-foreground sm:text-base">This workspace turns scattered quality signals into clear next actions across records, alerts, devices, exports, and collaboration.</p></div><div className="space-y-2"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium text-muted-foreground">Overall quality score</p><p className="text-3xl font-semibold">{data.summary.score}%</p></div><ProgressBar value={data.summary.score} /></div></div><div className="border-t border-border/60 bg-muted/25 p-6 sm:p-8 xl:border-l xl:border-t-0"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-3xl border border-border/60 bg-background/70 p-5"><DatabaseZap className="h-5 w-5 text-primary" /><p className="mt-4 text-3xl font-semibold">{data.summary.score}%</p><p className="mt-1 text-sm text-muted-foreground">Overall score</p></div><div className="rounded-3xl border border-border/60 bg-background/70 p-5"><AlertTriangle className="h-5 w-5 text-primary" /><p className="mt-4 text-3xl font-semibold">{data.summary.criticalItems}</p><p className="mt-1 text-sm text-muted-foreground">Critical gaps</p></div><div className="rounded-3xl border border-border/60 bg-background/70 p-5"><Activity className="h-5 w-5 text-primary" /><p className="mt-4 text-3xl font-semibold">{data.sections.length}</p><p className="mt-1 text-sm text-muted-foreground">Quality sections</p></div><div className="rounded-3xl border border-border/60 bg-background/70 p-5"><Sparkles className="h-5 w-5 text-primary" /><p className="mt-4 text-3xl font-semibold">{data.topActions.length}</p><p className="mt-1 text-sm text-muted-foreground">Top actions</p></div></div></div></div></CardContent></Card>
  <div className="grid gap-6 xl:grid-cols-[0.9fr_1.1fr]"><Card><CardHeader><CardTitle>Recommended cleanup queue</CardTitle><CardDescription className="mt-1">Highest-impact items to fix before sharing or exporting.</CardDescription></CardHeader><CardContent className="space-y-3">{data.topActions.length > 0 ? data.topActions.map((item) => <QualityActionCard key={item.id} item={item} />) : <div className="rounded-2xl border border-dashed border-border/70 p-5 text-sm text-muted-foreground">No cleanup actions detected right now.</div>}</CardContent></Card><Card><CardHeader><CardTitle>Quality section summary</CardTitle><CardDescription className="mt-1">Quick scan of where the record is strongest or weakest.</CardDescription></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2">{data.sections.map((section) => { const Icon = categoryIcons[section.id]; return <Link key={section.id} href={`#${section.id}`} className="rounded-2xl border border-border/60 bg-background/50 p-4 transition hover:bg-muted/40"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-primary" /><p className="text-sm font-semibold">{section.title}</p></div><StatusPill tone={section.tone}>{section.score}%</StatusPill></div><p className="mt-2 text-xs leading-5 text-muted-foreground">{section.items.length} action item{section.items.length === 1 ? "" : "s"}</p></Link>; })}</CardContent></Card></div>
  <div className="grid gap-6">{data.sections.map((section) => <div key={section.id} id={section.id}><QualitySectionCard section={section} /></div>)}</div><Card className="bg-background/40"><CardContent className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">Generated from existing VitaVault records</p><p className="mt-1 text-sm text-muted-foreground">No new database table is required. This patch computes the quality layer from profile, records, alerts, devices, reports, and care-team data.</p></div><Badge className="w-fit bg-background/70">Generated {data.summary.generatedAt.toLocaleString()}</Badge></CardContent></Card></div></AppShell>;
}
