export const JOB_KINDS = {
  ALERT_EVALUATION: "ALERT_EVALUATION",
  REMINDER_GENERATION: "REMINDER_GENERATION",
  DAILY_HEALTH_SUMMARY: "DAILY_HEALTH_SUMMARY",
  DEVICE_SYNC_PROCESSING: "DEVICE_SYNC_PROCESSING",
} as const;

export type JobKind = (typeof JOB_KINDS)[keyof typeof JOB_KINDS];