import { AppShell } from "@/components/app-shell";
import { requireUser } from "@/lib/session";
import { db } from "@/lib/db";
import { Button, Card, CardContent, CardHeader, CardTitle } from "@/components/ui";
import { formatDate, formatDateTime, bpLabel } from "@/lib/utils";

export default async function SummaryPage() {
  const user = await requireUser();
  const [profile, meds, appointments, labs, vitals] = await Promise.all([
    db.healthProfile.findUnique({ where: { userId: user.id } }),
    db.medication.findMany({ where: { userId: user.id }, include: { schedules: true }, orderBy: { createdAt: "desc" }, take: 10 }),
    db.appointment.findMany({ where: { userId: user.id }, orderBy: { scheduledAt: "desc" }, take: 10 }),
    db.labResult.findMany({ where: { userId: user.id }, orderBy: { dateTaken: "desc" }, take: 10 }),
    db.vitalRecord.findMany({ where: { userId: user.id }, orderBy: { recordedAt: "desc" }, take: 10 })
  ]);
  return <AppShell><div className="mb-6 flex items-center justify-between"><div><h2 className="text-3xl font-semibold">Printable Health Summary</h2><p className="text-sm text-muted-foreground">Use your browser print dialog to save this page as PDF.</p></div><Button onClick={() => {}}>Use Ctrl/Cmd + P</Button></div><div className="space-y-6"><Card><CardHeader><CardTitle>Patient overview</CardTitle></CardHeader><CardContent className="grid gap-2 text-sm md:grid-cols-2"><p>Name: {profile?.fullName ?? user.name ?? "—"}</p><p>Date of birth: {formatDate(profile?.dateOfBirth)}</p><p>Sex: {profile?.sex ?? "—"}</p><p>Blood type: {profile?.bloodType ?? "—"}</p><p>Height: {profile?.heightCm ?? "—"} cm</p><p>Weight: {profile?.weightKg ?? "—"} kg</p><p>Emergency contact: {profile?.emergencyContactName ?? "—"}</p><p>Emergency phone: {profile?.emergencyContactPhone ?? "—"}</p><p className="md:col-span-2">Chronic conditions: {profile?.chronicConditions ?? "—"}</p><p className="md:col-span-2">Allergies: {profile?.allergiesSummary ?? "—"}</p><p className="md:col-span-2">Notes: {profile?.notes ?? "—"}</p></CardContent></Card><Card><CardHeader><CardTitle>Medications</CardTitle></CardHeader><CardContent className="space-y-3 text-sm">{meds.map(item => <div key={item.id}><p className="font-medium">{item.name} • {item.dosage} • {item.frequency}</p><p className="text-muted-foreground">Times: {item.schedules.map(s => s.timeOfDay).join(", ")} | Start: {formatDate(item.startDate)} | End: {formatDate(item.endDate)}</p></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Appointments</CardTitle></CardHeader><CardContent className="space-y-3 text-sm">{appointments.map(item => <div key={item.id}><p className="font-medium">{item.purpose}</p><p className="text-muted-foreground">{item.doctorName} • {item.clinic} • {formatDateTime(item.scheduledAt)} • {item.status}</p></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Labs and recent vitals</CardTitle></CardHeader><CardContent className="grid gap-6 text-sm md:grid-cols-2"><div className="space-y-3">{labs.map(item => <div key={item.id}><p className="font-medium">{item.testName}</p><p className="text-muted-foreground">{formatDate(item.dateTaken)} • {item.resultSummary} • {item.flag}</p></div>)}</div><div className="space-y-3">{vitals.map(item => <div key={item.id}><p className="font-medium">{formatDateTime(item.recordedAt)}</p><p className="text-muted-foreground">BP {bpLabel(item.systolic, item.diastolic)} • HR {item.heartRate ?? "—"} • Sugar {item.bloodSugar ?? "—"} • Weight {item.weightKg ?? "—"}</p></div>)}</div></CardContent></Card></div></AppShell>;
}
